name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      
      - name: Check Flutter Version
        run: flutter --version

      - name: Clear Pub Cache
        run: flutter pub cache clean

      - name: Install dependencies
        run: flutter pub get

      # - name: Run tests
      #   run: dart test
